### ISSUE TITLE
Apigee Mixer Quota not working

### ISSUE THREAD

**Issue by aswinsegu** [apigee/istio-mixer-adapter#101]
Followed the steps of including quota as 5 requests per minute, but the same is not reflecting in the microservice. Could not get RESOURCE_EXHAUSTED:apigee-handler.apigee.istio-system:quota exceeded.

Is this only at the nightly build as of now?

**Comment by theganyo** [comment]
Are you running the new 1.0 alpha-2 release?

**Comment by aswinsegu** [comment]
I am using Alpha 1 release

**Comment by theganyo** [comment]
I’m not sure what you’re running into, but I suggest moving to alpha-2.

**Comment by theganyo** [comment]
I'm going to close this. If you see new issues in alpha-2, please open a new issue. Thanks!
