### ISSUE TITLE
allow api keys in external auth token

### ISSUE THREAD

**Issue by srinandan** [apigee/istio-mixer-adapter#129]
Here is a scenario:
Customer has an external auth server that generates oauth auth tokens (they must be JWT based). This external auth server can add a claim for the Apigee API Key. 

The user must be able to tell the adapter in which claim the api key is contained in the JWT. Once Envoy has validated the JWT, the adapter will run api key verification on the claim.

**Comment by galo** [comment]
There are a couple of claims used currently by the adapter, such as api_product_list and application_name, that are likely not in the tokens generated by other oauth servers, and possible impossible to map.

**Comment by theganyo** [comment]
Ok. Here's how it will work:
1. Operator adds a config item in the handler. eg. `api_key_claim:  apikeyfield` where apikeyfield is any string valid for a JWT claim
2. JWT token validated per Istio auth policy
3. adapter checks passed JWT claims for `apikeyfield`
    a. if present, auth treats as if api_key had been passed directly, no other JWT claims are considered
    b. if not present, auth falls back to normal JWT token behavior so properly formatted JWT tokens can still work

Sound good?

**Comment by galo** [comment]
LGTM

**Comment by theganyo** [comment]
The final precedence of all auth methods will match this :
1. If JWT w/ API Key - use API Key in claims
2. API Key - use API Key
3. JWT token - use JWT claims

If any method is provided but fails, the next available one(s) will be attempted. If all provided methods fail, the request will be rejected.
