### ISSUE TITLE
allow masking of ax

### ISSUE THREAD

**Issue by srinandan** [apigee/istio-mixer-adapter#136]
A customer may have sensitive data in the path (or query params). In some situations the customer may also want to not send client IPs to analytics (considered PII). We should provide the ability to mask:

1. URI and Path
2. Client IP

If this configuration can be done in the definition (kind: analytics) and not require code changes, then we should document the procedure on how to achieve this. Finally, can I have two definitions - one that masks and one that doesn't and apply them on services depending on the sensitivity of the service?

**Comment by theganyo** [comment]
Yes, the following can all be done in Istio config. These are in the definitions.yaml:

    client_ip: source.ip | ip("0.0.0.0")
    request_uri: request.path | ""
    request_path: request.path | ""

To "mask" them, you can change them to constants:

    client_ip: ip("0.0.0.0")
    request_uri: ""
    request_path: ""

If you want some analytics masked and others not, you should be able to create two definitions, say: `kind: analytics` and `kind: maskedanalytics`. Then, you'd create appropriate rules to invoke the correct `analytics` or `maskedanalytics` instances.

**Comment by srinandan** [comment]
That's perfect. In that case, we can either document this or add this to the same `definitions.yaml` as a new kind..

**Comment by theganyo** [comment]
@WWitman for docs
