### ISSUE TITLE
support for custom VH

### ISSUE THREAD

**Issue by srinandan** [apigee/istio-mixer-adapter#14]
In the yaml file here: https://github.com/apigee/istio-mixer-adapter/blob/master/install/apigee-handler.yaml, add support for management url (opdk install will have custom management urls)

**Comment by theganyo** [comment]
I believe this should just be a doc issue.

**Comment by srinandan** [comment]
It is not just a docs issue. 

Assumption that virtual hosts are always _{org}-{-env}.apigee.net_ is not always true. Customers have custom virtual hosts. We need a method to specify the edgemicro-auth url.

I think the issue title is wrong. it is not just for OPDK.

**Comment by theganyo** [comment]
The `customer_base` url is the `edgemicro-auth` url. There is no assumption of the`{org}-{-env}.apigee.net` format that you mentiond.

**Comment by srinandan** [comment]
fair point. closing the issue.
