### ISSUE TITLE
CLI: unexpected error during provisioning

### ISSUE THREAD

**Issue by theganyo** [apigee/istio-mixer-adapter#160]
Reported by diegozuluaga@google.com:

Error running provision on alpha-3:
```
apigee-istio provision -o testmyapi -e test -u **** -p ***** > samples/apigee/handler.yaml

panic: runtime error: invalid memory address or nil pointer dereference[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7bba0e]
```
On Apigee: kvm(istio) and api proxy (istio-auth) are there. API Proxy didn't deploy(red triangle).

Output with verbose:
```
HTTP/1.1 404 Not Found
Content-Length: 167
Connection: keep-alive
Content-Type: application/json
Date: Wed, 18 Jul 2018 21:20:39 GMT
Server: Apigee LB

{
  "code" : "messaging.config.beans.ApplicationDoesNotExist",
  "message" : "APIProxy named istio-auth does not exist in organization testmyapi",
  "contexts" : [ ]
}

    "available": 0,
    "expiryTime": 0,
    "timestamp": 1531948912314
}

verifying customer proxy...
GET /istio-auth/certs HTTP/1.1^M
Host: testmyapi-test.apigee.net^M
User-Agent: Go-http-client/1.1^M
Accept-Encoding: gzip
```

When provisioning fails as above, it must fail with a good error message.

**Comment by dzuluaga** [comment]
Switching to another trial org did the trick. API Proxy is deployed okay, KVM got created, and handler.yaml contains the right output. It'd be nice to return a more descriptive and less alarming message. Thanks for the help.

**Comment by theganyo** [comment]
Unfortunately, there isn't quite enough context in the verbose output here to fully determine the issue and if I've fixed it. If this happens again after this fix, hopefully we can capture a bit more of the log.
