### ISSUE TITLE
auth proxy /products endpoint fails to escape double quotes

### ISSUE THREAD

**Issue by wongjoey** [apigee/istio-mixer-adapter#161]
Executing the apigee-istio tool to list bindings exits with an exception if an API Product exists in the ORG+ENV with a description which has characters that need to be escaped.

# apigee-istio -o <ORG> -e <ENV> bindings list
error retrieving products: invalid character '1' after object key:value pair

Problem seems to be the listing call returns a JSON payload and the values in the payload are not escaped.

**Comment by theganyo** [comment]
Do you have an example org or env name that this is an issue for?

**Comment by theganyo** [comment]
Tried recreating issue with quotes and brackets and such in product descriptions without success. Closing as unable to recreate. @wongjoey If you can provide an example, please do and I'll reopen.

**Comment by theganyo** [comment]
I've been able to recreate. The auth proxy's /products endpoint fails to escape double quotes in the user-entered api product values.

**Comment by theganyo** [comment]
@srinandan has a fix. we just need the new `istio-products-javacallout-2.0.0.jar` from him.
