### ISSUE TITLE
How to pass on the APIGEE OAuthScopes to the Upstream backend after authorization

### ISSUE THREAD

**Issue by saratkoganti** [apigee/istio-mixer-adapter#203]
I'm wondering, how can we make apigee-mixer to forward Scopes to Upstream backend so that backend can have some logic to allow certain scopes to do certain operations?

**Comment by theganyo** [comment]
You could add your scopes as a header. See: https://istio.io/docs/reference/config/istio.networking.v1alpha3/#HTTPRoute
