### ISSUE TITLE
Unable to import istio-auth proxy

### ISSUE THREAD

**Issue by Luis-Angel-Ramher** [apigee/istio-mixer-adapter#204]
I have tried with the different versions for the adapter apigee-istio but I do not get it. 
I write:

``
apigee-istio provision -o my_org -e test -u username -p password
``
and he returns me
``
error deploying auth proxy: error importing proxy istio-auth: POST https://api.enterprise.apigee.com/v1/o/my-org/apis?action=import&name=istio-auth: 400 Bundle is invalid. Empty bundle
``

**Comment by srinandan** [comment]
looks like the org name is not right. did you get past this error?
