### ISSUE TITLE
Include this adapter in Istio adapters list?

### ISSUE THREAD

**Issue by theganyo** [apigee/istio-mixer-adapter#22]
See: https://istio.io/docs/reference/config/adapters/

**Comment by gbrail** [comment]
Yes.

@srinandan can you work with the Istio PM team on this? Or better yet just submit a PR for Istio.

Right now, in there I see:

Stackdriver
Solarwinds
Prometheus
Dogstatsd
Circonus

all of which are open source adapters to products that are not necessarily open source, but which are included in the standard Mixer.

https://github.com/istio/istio/blob/master/mixer/adapter/inventory.yaml

**Comment by theganyo** [comment]
Simply pushing our code into the Istio repo will create code ownership, versioning, and support issues. I'm convinced this would not be a good idea. However, we should certainly discuss these issues with the Istio team.

**Comment by srinandan** [comment]
once the mixer adapter architecture changes (so that vendor adapters can run in a separate process), I  suspect this issue will be automatically settled.

**Comment by theganyo** [comment]
Replaced by https://github.com/apigee/istio-mixer-adapter/issues/107
