### ISSUE TITLE
Issue with JWT Example

### ISSUE THREAD

**Issue by Zee-Khan** [apigee/istio-mixer-adapter#223]
When attempting to create a JWT token, I'm getting a 500.

`./apigee-istio token create -o {org} -e {env} -i {key_from_handler} -s {secret_from_handler}`

Executing it as a curl, I get 
`{"fault":{"faultstring":"XMLToJSON[Products-to-JSON]: Source AccessEntity.ChildNodes.Access-App-Info.App.Credentials.Credential.ApiProducts is not available","detail":{"errorcode":"steps.xml2json.SourceUnavailable"}}}`

Also, I assumed this `https://{your organization}-{your environment}.apigee.net/istio-auth/token` GET endpoint would return a token, but instead, I get an invalid request error.

**Comment by theganyo** [comment]
Can you try this release: https://github.com/apigee/istio-mixer-adapter/releases/tag/1.0.3-2? Hopefully it addresses your issue.

**Comment by Zee-Khan** [comment]
I'm still getting the same error with that release.

**Comment by Zee-Khan** [comment]
Oh for the creating of the jwt I used POST.

Here's the output with the verbose flag.

> root@pks-client:~/apigee/1.0.3# ./apigee-istio token create -o zohaibkhan-eval -e prod -i {redacted} -s {redacted} --verbose
> POST /istio-auth/token HTTP/1.1
> Host: zohaibkhan-eval-prod.apigee.net
> User-Agent: Go-http-client/1.1
> Content-Length: 198
> Accept: application/json
> Content-Type: application/json
> Accept-Encoding: gzip
> 
> {"client_id":"{redacted}","client_secret":"{redacted}","grant_type":"client_credentials"}
> 
> 
> HTTP/1.1 500 Internal Server Error
> Content-Length: 217
> Connection: keep-alive
> Content-Type: application/json
> Date: Wed, 19 Dec 2018 23:30:15 GMT
> 
> {"fault":{"faultstring":"XMLToJSON[Products-to-JSON]: Source AccessEntity.ChildNodes.Access-App-Info.App.Credentials.Credential.ApiProducts is not available","detail":{"errorcode":"steps.xml2json.SourceUnavailable"}}}
> 
> error creating token: error creating token: POST https://zohaibkhan-eval-prod.apigee.net/istio-auth/token: 500

The GET that I was trying was for this part of the authentication-policy.yaml

> - jwt:
>       issuer: https://redacted-redacted.apigee.net/istio-auth/token
>       jwks_uri: https://redacted-redacted.apigee.net/istio-auth/certs

My assumption is that performing a GET on these endpoints retrieves data. The jwks_uri does return a JSON with the keys while the issuer returns the following JSON.

>  {
>                   "error":"invalid_request",
>                   "error_description": "invalid request"
>                 }

**Comment by theganyo** [comment]
When you updated your release, did you run the provision with the `--forceProxyInstall` flag?

**Comment by Zee-Khan** [comment]
Just tried it with `--forceProxyInstall` and it works on version 1.0.3.

**Comment by theganyo** [comment]
Excellent. I'll make a note in the release notes to be sure to use that flag for upgrades.
