### ISSUE TITLE
Question on apigee-istio provision step

### ISSUE THREAD

**Issue by rprakashg** [apigee/istio-mixer-adapter#226]
./apigee-istio provision -o tmobilea -e "sb06" -u "{myuserid}" -p "{my password}" > samples/apigee/handler.yaml

WARNING: Apigee may not be provisioned properly.
Unable to verify proxy endpoint(s). Errors:

  GET https://tmobilea-sb06.apigee.net/istio-auth/certs: 401
  GET https://tmobilea-sb06.apigee.net/istio-auth/products: 401

From the above error seems like there is some configuration or permission required on apigee side. Can someone share details on what role/permission that the user running the above command needs to have on apigee edge?

**Comment by rprakashg** [comment]
I just checked my permissions I am an Org Administrator. Not sure if this is related to permission issue now

**Comment by theganyo** [comment]
Try running with `--verbose`. Hopefully that will give you insight.

**Comment by rprakashg** [comment]
Tried nothing more than without --verbose switch
