### ISSUE TITLE
move the apigee-istio cli source to a seperate repo 

### ISSUE THREAD

**Issue by rprakashg** [apigee/istio-mixer-adapter#227]
Move the apigee-istio CLI source to a seperate repo so folks can easily enhance and improve this.

**Comment by rprakashg** [comment]
I'm trying to rebuild the apigee-istio cli as I'm having some issues with provision command and realized it would be super helpful if it was a seperate repo

**Comment by theganyo** [comment]
Generally, you should be able to build the CLI for your platform simply by running:

`go build`

from the `istio-mixer-adapter/apigee-istio` directory

**Comment by theganyo** [comment]
Alternatively, you could run:

`DRYRUN=1 bin/build_release.sh`

This will create binaries for all platforms in the `dist/` directories.

**Comment by rprakashg** [comment]
Issue is not building the code, just would be nice to have it seperate rep, dep ensure takes a long time to pull down all the dependencies that are used in the rest of the codebase

**Comment by theganyo** [comment]
This isn't going to be a priority.
