### ISSUE TITLE
UNAVAILABLE:upstream connect error or disconnect/reset before headers 

### ISSUE THREAD

**Issue by Zee-Khan** [apigee/istio-mixer-adapter#231]
I get inconsistent responses from the same endpoint request. 

![screen shot 2019-01-15 at 9 46 47 am](https://user-images.githubusercontent.com/2704184/51202691-2aa2c100-18b4-11e9-9ad4-40b2142784fe.png)

**Comment by theganyo** [comment]
There have been some issues in Istio with inconsistent response caching, especially in earlier releases. Try moving to the latest release if you can.
