### ISSUE TITLE
Unable to Configure OPDK from Adapter

### ISSUE THREAD

**Issue by aswinsegu** [apigee/istio-mixer-adapter#236]
While trying to provision Istio Mixer Adapter 1.0.4 to Apigee OPDK installation, found that a http call is made to {org}-{env}.apigee.net, even though the provision command had managementBase as CLI argument. Attached Screenshot for reference

![imageedit__6911511905](https://user-images.githubusercontent.com/10217586/52486948-7bbb8180-2be2-11e9-87d7-00f90b8d0b0e.png)

Let us know if you need any details

**Comment by theganyo** [comment]
Have you also tried specifying `--routerBase` ?

**Comment by aswinsegu** [comment]
Did not try this one, as per documentation of the Mixer Adapter for OPDK, we only needed --managementBase. Is this necessary as well?

**Comment by marutichand** [comment]
Try this ./apigee-istio -u trial@apigee.com -p xxxxxxx -o trial -e test -r http://localhost:9001 -m http://localhost:8080 provision -v

**Comment by aswinsegu** [comment]
We followed the steps on Istio Adapter github page, but -r is not mentioned there.
Will check and update on the same

**Comment by sidd-harth** [comment]
-r option with the router (API endpoint) should work.
Check this article,
https://community.apigee.com/articles/65504/configuring-istio-mixer-adapter-with-opdk-418xx-an.html
