### ISSUE TITLE
Folder "samples/istio/" is absent

### ISSUE THREAD

**Issue by kisterov** [apigee/istio-mixer-adapter#244]
Hello,

On the last release 1.0.6, in the Linux archive bellow,

https://github.com/apigee/istio-mixer-adapter/releases/download/1.0.6/istio-mixer-adapter_1.0.6_linux_64-bit.tar.gz

Folder "samples/istio/" is absent, as well as mentioned files:

samples/istio/istio-demo-auth.yaml
[samples/istio/istio-demo.yaml
<img width="1016" alt="screen shot 2019-02-18 at 4 37 12 pm" src="https://user-images.githubusercontent.com/47747919/52957902-84a71280-339b-11e9-9dcb-9ff08a082e41.png">
<img width="1668" alt="screen shot 2019-02-18 at 4 16 24 pm" src="https://user-images.githubusercontent.com/47747919/52957912-8a045d00-339b-11e9-8c15-2fba28b29d09.png">

**Comment by theganyo** [comment]
Thanks for the heads up, the reference has been removed from the README here and Apigee docs.
