### ISSUE TITLE
Changing quota settings causes "incompatible quota buckets" error

### ISSUE THREAD

**Issue by carlosaml** [apigee/istio-mixer-adapter#254]
When the quota settings from an API product change the adapter will cause all requests to return a 500 error for ~10 minutes with the following payload: `INTERNAL:performing check operation failed: 1 error occurred:%0A%0A* incompatible quota buckets`.

The adapter logs have the following error messages:
```
error	api	Check failed:performing check operation failed: 1 error occurred:

* incompatible quota buckets
```

I have reproduced this same issue on both the 1.0.6 Docker image based mixer adapter as well as the newer gRPC adapter on Istio 1.1.

Steps to reproduce the issue:
- set a quota in a product (the quota will kick in the next time the adapter fetches the product data)
- change the quota settings 
- watch all requests fail

After 10 minutes it starts working again, which coincides with the deleteAfter parameter on the quota manager: https://github.com/apigee/istio-mixer-adapter/blob/master/adapter/quota/manager.go#L34

**Comment by patrickmcmichael** [comment]
Our understanding is that quota counters are ticked down per client, and based on last fetched value. It sounds like existing clients are impacted by changes to the configured value even though they should be ticking down their existing counter independent of changes behind the scenes.

**Comment by theganyo** [comment]
Thanks for the report. It is absolutely inappropriate for the quota to be failing in this condition. Instead, it should drop the local bucket in favor of the server settings. I'm on it.

**Comment by theganyo** [comment]
The latest nightly build now has a fix for this. You may try it out if you'd like:

Adapter for Istio 1.1:
```
gcr.io/apigee-api-management-istio/apigee-adapter:nightly
```

Mixer image for Istio 1.0:
```
gcr.io/apigee-api-management-istio/istio-mixer:nightly"
```

Thanks!

**Comment by carlosaml** [comment]
Thanks for the quick turnaround @theganyo, I did some quick testing and the issue seems to have been fixed.

**Comment by theganyo** [comment]
Thanks for verifying, @carlosaml. I'll plan a new release soon.
