### ISSUE TITLE
1.1.0:the auth doesn't take effect

### ISSUE THREAD

**Issue by walkerline** [apigee/istio-mixer-adapter#263]
We just installed the 1.1.0 adapter. However, it does not seem like the authentication get applied. When I tried to curl hellowworld service after applying the adapter, I did not get any authentication challenge and the request just went through.

Then I figured out the two instances defined in the rule.yaml were not applied to the istio environment.

`kubectl get crd -listio=mixer-instance`

NAME                             CREATED AT
analytics.config.istio.io        2019-03-11T10:56:35Z
apikeys.config.istio.io          2019-03-21T15:11:48Z
authorizations.config.istio.io   2019-03-21T15:11:48Z
checknothings.config.istio.io    2019-03-21T15:11:48Z
edges.config.istio.io            2019-03-21T15:11:49Z
instances.config.istio.io        2019-03-21T15:11:49Z
kuberneteses.config.istio.io     2019-03-21T15:11:48Z
listentries.config.istio.io      2019-03-21T15:11:49Z
logentries.config.istio.io       2019-03-21T15:11:49Z
metrics.config.istio.io          2019-03-21T15:11:49Z
quotas.config.istio.io           2019-03-21T15:11:49Z
reportnothings.config.istio.io   2019-03-21T15:11:49Z
tracespans.config.istio.io       2019-03-21T15:11:49Z

Is there anyway I can debug this?

**Comment by AshishThakur** [comment]
I am observing a similar behaviour using istio-1.1.0 version on apigee cloud.

**Comment by theganyo** [comment]
Which authentication? If you installed the [authentication policy](https://github.com/apigee/istio-mixer-adapter/blob/master/samples/apigee/authentication-policy.yaml) and nothing happened (after a reasonable time to take effect), there is a problem with the base Istio install or configuration.

If you aren't using the JWT authentication policy, you are relying on Mixer policy to do authentication. Read on.

1. Which install instructions are you following? Istio 1.1 has changed dramatically from 1.0 and Mixer policy checks are not on by default. Be sure they are! As noted in the [README](https://github.com/apigee/istio-mixer-adapter/blob/master/README.md) here, you can get more information [here](https://istio.io/docs/tasks/policy-enforcement/enabling-policy/).

2. Check the mixer logs as [explained here](https://github.com/apigee/istio-mixer-adapter/wiki/Mixer-logging-and-metrics). You shouldn't see errors even at the default logging setting.

**Comment by theganyo** [comment]
Oh... I'm not certain the title of this issue is an accurate diagnosis. Just FYI, to check if the mixer instances are actually running in the mesh, I would use this command:

`kubectl -n istio-system get pods -l chart=mixer`

**Comment by walkerline** [comment]
so we are just simply testing the helloworld case following the steps in the installation documentation of adpater 1.1.0

Here are the steps to reproduce the issue:
1. we installed the helloworld service.
2. we then were able to curl the helloworld serivce as expected
3. We apply the istio mixer by running below
 `kubectl apply -fsamples/helloworld/helloworld-gateway.yaml`
4. We then are still able to curl the helloworld service without getting any permission or authentication challange.

Thats y we checked our mixer and we do not see we have the apigee related mixer instances come up.

We do not see any error message in mixer log and we do not see from apigee side any request comes to istio-auth proxy.

If we run 
`kubectl -n istio-system get pods -l chart=mixer`

We see below

NAME                               READY   STATUS    RESTARTS   AGE
istio-policy-7b49f77cb-k87np       2/2     Running   2          27h
istio-telemetry-7b784cf55d-7vfb6   2/2     Running   1          27h

**Comment by theganyo** [comment]
Great, thanks for clarifying your process! So it looks like you got Istio and helloworld installed correctly...  But I see nothing in the steps you gave that installs and configures the Apigee adapter. Please follow the [README](https://github.com/apigee/istio-mixer-adapter/blob/master/README.md) and follow the Istio 1.1 steps. Basically, you will:

1. [provision Apigee for Istio](https://github.com/apigee/istio-mixer-adapter/blob/master/README.md#provision-apigee-for-istio)
2. [configure Istio for Apigee](https://github.com/apigee/istio-mixer-adapter/blob/master/README.md#configure-istio-for-the-apigee-adapter)
3. [configure Apigee policy](https://github.com/apigee/istio-mixer-adapter/blob/master/README.md#apigee-policies)

**Comment by walkerline** [comment]
Hi, 

We strictly followed the steps on the 1.1 adapter documentation. We did the provision and configuration with no issues.

Do we even need to configure APIGEE policy for that helloworld case? I do not see the step for testing the helloworld require to configure apigee policy.

Thanks

**Comment by theganyo** [comment]
You're right, that shouldn't matter at this point. Let's just continue debugging, then...

`kubectl -n istio-system get svc -l app=apigee-adapter`

There should be 1 service.

`kubectl -n istio-system get po -l app=apigee-adapter`

There should be 2 pod instances.

`kubectl -n istio-system get rule apigee-rule -o json`

This should match the rule you applied.

`kubectl -n istio-system get handler apigee-handler -o json`

This should include your Apigee configuration.

**Comment by walkerline** [comment]
Here you go:
`kubectl -n istio-system get svc -l app=apigee-adapter`
NAME             TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
apigee-adapter   ClusterIP   10.103.173.67   <none>        5000/TCP   14h

`kubectl -n istio-system get po -l app=apigee-adapter`
NAME                              READY   STATUS    RESTARTS   AGE
apigee-adapter-7ddbbb7645-jfmcb   1/1     Running   0          14h
apigee-adapter-7ddbbb7645-zzvlx   1/1     Running   0          14h

`ubectl -n istio-system get rule apigee-rule -o json`
{
    "apiVersion": "config.istio.io/v1alpha2",
    "kind": "rule",
    "metadata": {
        "annotations": {
            "kubectl.kubernetes.io/last-applied-configuration": "{\"apiVersion\":\"config.istio.io/v1alpha2\",\"kind\":\"rule\",\"metadata\":{\"annotations\":{},\"name\":\"apigee-rule\",\"namespace\":\"istio-system\"},\"spec\":{\"actions\":[{\"handler\":\"apigee-handler\",\"instances\":[\"apigee-authorization\",\"apigee-analytics\"]}],\"match\":\"context.reporter.kind == \\\"inbound\\\" \\u0026\\u0026 destination.namespace == \\\"default\\\"\"}}\n"
        },
        "creationTimestamp": "2019-03-22T06:10:15Z",
        "generation": 1,
        "name": "apigee-rule",
        "namespace": "istio-system",
        "resourceVersion": "11051643",
        "selfLink": "/apis/config.istio.io/v1alpha2/namespaces/istio-system/rules/apigee-rule",
        "uid": "28c5ab80-4c69-11e9-8530-0050569bf5da"
    },
    "spec": {
        "actions": [
            {
                "handler": "apigee-handler",
                "instances": [
                    "apigee-authorization",
                    "apigee-analytics"
                ]
            }
        ],
        "match": "context.reporter.kind == \"inbound\" \u0026\u0026 destination.namespace == \"default\""
    }
}

`kubectl -n istio-system get handler apigee-handler -o json`

Error from server (NotFound): handlers.config.istio.io "apigee-handler" not found


The last one we see an error here.

Then I ran below:
`kubectl -n istio-system logs istio-policy-7b49f77cb-k87np   mixer |grep error`

2019-03-21T15:18:55.422026Z	error	Handler not found: handler='apigee-handler'
2019-03-21T15:18:55.422053Z	error	No valid actions found in rule
2019-03-21T15:19:05.530508Z	error	adapters	adapter did not close all the scheduled daemons	{"adapter": "prometheus.istio-system"}
2019-03-22T06:05:26.601204Z	error	unable to find template 'apigee-authorization'
2019-03-22T06:05:26.601370Z	error	template 'apigee-authorization' not found
2019-03-22T06:05:26.603739Z	error	Handler not found: handler='apigee-handler'
2019-03-22T06:05:26.603798Z	error	No valid actions found in rule
2019-03-22T06:05:27.745549Z	error	unable to find template 'apigee-authorization'
2019-03-22T06:05:27.745596Z	error	template 'apigee-authorization' not found
2019-03-22T06:10:03.256244Z	error	unable to find template 'apigee-authorization'
2019-03-22T06:10:03.256307Z	error	template 'apigee-authorization' not found
2019-03-22T06:10:06.806012Z	error	unable to find template 'apigee-analytics'
2019-03-22T06:10:06.806044Z	error	template 'apigee-analytics' not found
2019-03-22T06:10:17.125847Z	error	Handler not found: handler='apigee-handler'
2019-03-22T06:10:17.125895Z	error	No valid actions found in rule

**Comment by theganyo** [comment]
Ok. Now we're getting somewhere. It just looks like the definitions were not applied properly to Istio for some reason. Try running this from the adapter directory:

`kubectl apply -f samples/grpc/definitions.yaml`

**Comment by walkerline** [comment]
done, its there already and i deleted it and re-applied

but no change, errors still there:

2019-03-22T21:03:49.681508Z	error	unable to find template 'apigee-analytics'
2019-03-22T21:03:49.683583Z	error	template 'apigee-analytics' not found
2019-03-22T21:03:49.683721Z	error	Handler not found: handler='apigee-handler'
2019-03-22T21:03:49.683737Z	error	No valid actions found in rule
2019-03-22T21:03:51.356345Z	error	Handler not found: handler='apigee-handler'
2019-03-22T21:03:51.356377Z	error	No valid actions found in rule

**Comment by theganyo** [comment]
Interesting. I can recreate your errors by deleting the definitions.yaml and killing the mixer pod. But then when I apply the definitions.yaml, it repairs itself:

```
2019-03-22T21:26:35.563595Z	info	grpcAdapter	Connected to: apigee-adapter:5000
2019-03-22T21:26:35.564377Z	info	ccResolverWrapper: sending new addresses to cc: [{apigee-adapter:5000 0  <nil>}]
2019-03-22T21:26:35.564501Z	info	base.baseBalancer: got new resolved addresses: [{apigee-adapter:5000 0  <nil>}]
2019-03-22T21:26:35.564620Z	info	base.baseBalancer: handle SubConn state change: 0xc421ad40c0, CONNECTING
2019-03-22T21:26:35.655881Z	info	base.baseBalancer: handle SubConn state change: 0xc421ad40c0, READY
```

Once this happens, the auth also takes effect. If your mixer isn't getting the updates, perhaps you can try killing the mixer pods and letting them restart.

**Comment by walkerline** [comment]
so I restarted the two mixer pods(policy and telemetry)

Then I ran `kubectl -n istio-system logs istio-policy-7b49f77cb-5mmqj mixer |grep error`

This is the output:
2019-03-22T21:39:14.244244Z	error	Handler not found: handler='apigee-handler'
2019-03-22T21:39:14.244278Z	error	No valid actions found in rule

One thing i want to mention here: our K8s cluster has PSP installed. we enabled CNI plugin and we created our own service binding roles so that we can enventually install istio. Not sure if that matters.

Thanks

**Comment by theganyo** [comment]
I don't know if that would have anything to do with this or not, but it appears that Mixer is unable to see the CRDs for some reason. Would you be able to shared your logs from Mixer and Galley?

**Comment by walkerline** [comment]
[Logs.zip](https://github.com/apigee/istio-mixer-adapter/files/2998770/Logs.zip)

Ok, attached, please take a look

**Comment by walkerline** [comment]
[gally-log.txt](https://github.com/apigee/istio-mixer-adapter/files/2999287/gally-log.txt)
[telemetry-mixer-log.txt](https://github.com/apigee/istio-mixer-adapter/files/2999288/telemetry-mixer-log.txt)
[policy-mixer-log.txt](https://github.com/apigee/istio-mixer-adapter/files/2999289/policy-mixer-log.txt)

Please help to take a look

**Comment by theganyo** [comment]
Can you post your handler file here? (obscure your key and secret) Also, can you please run the `kubectl apply` again on that file again and see if you get any errors?

**Comment by AshishThakur** [comment]
@theganyo please find the handler file. @walkerline and I work together. key, secret, apigee_base, customer_base have been obscured.
``` 
# Istio handler configuration for Apigee gRPC adapter for Mixer
# generated by apigee-istio provision on 2019-03-18 17:02:25
apiVersion: config.istio.io/v1alpha2
kind: apigee
metadata:
  name: apigee-handler
  namespace: istio-system
spec:
  adapter: apigee
  connection:
    address: apigee-adapter:5000
  params:
    apigee_base: http://dev-sandbox-lx300.amdc.example.com:9001/edgemicro
    customer_base: http://dev-sandbox-lx300.amdc.example.com:9001/istio-auth
    org_name: testorg
    env_name: sandbox
    key: key
    secret: secret
    analytics:
      legacy_endpoint: true
```

**Comment by theganyo** [comment]
I think I see the problem. Please try this: Change the 4th line of that file from:

`kind: apigee`

to:

`kind: handler`

Then apply the file again. Let me know if that clears things up.

**Comment by AshishThakur** [comment]
@theganyo i see another interesting behaviour for apigee cloud. Here we have ```kind: apigee``` and  ```  adapter: handler``` which is different from our on-premises apigee. Is this expected?
```
# Istio handler configuration for Apigee gRPC adapter for Mixer
# generated by apigee-istio provision on 2019-03-26 14:42:39
apiVersion: config.istio.io/v1alpha2
kind: apigee
metadata:
  name: apigee-handler
  namespace: istio-system
spec:
  adapter: handler
  connection:
    address: apigee-adapter:5000
  params:
    apigee_base: https://istioservices.apigee.net/edgemicro
    customer_base: https://ashishthakur-eval-prod.apigee.net/istio-auth
    org_name: ashishthakur-eval
    env_name: prod
    key: ***
    secret: ***
```

**Comment by AshishThakur** [comment]
Reply for https://github.com/apigee/istio-mixer-adapter/issues/263#issuecomment-476471268. Thanks this fixes the issue and we are able to see the handler though the rules are still not reflecting which we are trying to debug.

**Comment by walkerline** [comment]
So i think its still not working for us on our on-prem k8s environment.

kubectl -n istio-system logs istio-policy-7b49f77cb-k87np mixer |grep error

![image](https://user-images.githubusercontent.com/11176360/54993880-4bb11d80-4f99-11e9-9fda-99f06db3dd31.png)

**Comment by theganyo** [comment]
Sorry, didn't mean to close this. Just so I understand: You now have one environment that's working and one that isn't - using the same configuration?

**Comment by AshishThakur** [comment]
yes you are correct.

**Comment by theganyo** [comment]
So... One would have to believe that the environment is to blame (or the configuration is actually still different). So, I'm unsure of where to begin with this. Have you tried turning it off and on again? ;) But seriously... what precisely, is different between the environments?

**Comment by AshishThakur** [comment]
The one where it is not working is a on-prem k8S cluster with Pod Security Policy(PSP) enabled and for this we use an on-prem apigee(Apigee Private Cloud). Would PSP cause this? Apart from this there isn't any difference. We did try turning it off and on again.

**Comment by walkerline** [comment]
Sorry for the confusion, @theganyo, so the cloud is just a test environment that @AshishThakur has. So please ignore it, the issue happens only on our on-prem K8s cluster and we are still having the issue. So we can just focus on the issue on this environment.

Let us know if anything else you need from us.

**Comment by theganyo** [comment]
It seems significant that you have got it working in one environment, though. I haven't worked with PSP... Would it be possible to try without PSP enabled (or disable it) to verify that is or is not the underlying cause?

**Comment by theganyo** [comment]
Well, let's back up a bit. Now that you've fixed the handler file and applied it, you should be able to see it in kubernetes with this:

`kubectl -n istio-system get handler apigee-handler -o json`

Yes?

**Comment by walkerline** [comment]
Yes, this is the output:

`{
    "apiVersion": "config.istio.io/v1alpha2",
    "kind": "handler",
    "metadata": {
        "annotations": {
            "kubectl.kubernetes.io/last-applied-configuration": "{\"apiVersion\":\"config.istio.io/v1alpha2\",\"kind\":\"handler\",\"metadata\":{\"annotations\":{},\"name\":\"apigee-handler\",\"namespace\":\"istio-system\"},\"spec\":{\"adapter\":\"apigee\",\"connection\":{\"address\":\"apigee-adapter:5000\"},\"params\":{\"analytics\":{\"legacy_endpoint\":true},\"apigee_base\":\"http://dev-sandbox-lx300.amdc.mckinsey.com:9001/edgemicro\",\"customer_base\":\"http://dev-sandbox-lx300.amdc.mckinsey.com:9001/istio-auth\",\"env_name\":\"sandbox\",\"key\":\"dc854468d8b950b6012a0b69d754d692d20e8290f6722bf3ae777d7f5fe9f3a0\",\"org_name\":\"testorg\",\"secret\":\"c9cbbc6e94a2d1647a65ca19ca4daaaf17757c1a94ccb9dcf3f710a28f0ca949\"}}}\n"
        },
        "creationTimestamp": "2019-03-26T11:50:58Z",
        "generation": 1,
        "name": "apigee-handler",
        "namespace": "istio-system",
        "resourceVersion": "13097547",
        "selfLink": "/apis/config.istio.io/v1alpha2/namespaces/istio-system/handlers/apigee-handler",
        "uid": "6bc896da-4fbd-11e9-917a-0050569bf5da"
    },
    "spec": {
        "adapter": "apigee",
        "connection": {
            "address": "apigee-adapter:5000"
        },
        "params": {
            "analytics": {
                "legacy_endpoint": true
            },
            "apigee_base": "http://dev-sandbox-lx300.com:9001/edgemicro",
            "customer_base": "http://dev-sandbox-lx300.com:9001/istio-auth",
            "env_name": "sandbox",
            "key": "key",
            "org_name": "testorg",
            "secret": "secret"
        }
    }
}
`

**Comment by walkerline** [comment]
and we now see below error in the mixer

`2019-03-26T11:49:47.998989Z	info	grpc: addrConn.createTransport failed to connect to {apigee-adapter:5000 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 10.103.149.12:5000: connect: connection refused". Reconnecting...
2019-03-26T11:49:49.012973Z	info	grpc: addrConn.createTransport failed to connect to {apigee-adapter:5000 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp: lookup apigee-adapter on 10.96.0.10:53: server misbehaving". Reconnecting...
2019-03-26T11:49:50.786409Z	info	grpc: addrConn.createTransport failed to connect to {apigee-adapter:5000 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 10.103.149.12:5000: connect: no route to host". Reconnecting...
2019-03-26T11:50:28.736373Z	error	unable to find template 'apigee-analytics'
2019-03-26T11:50:28.738277Z	error	template 'apigee-analytics' not found
2019-03-28T21:24:22.685087Z	error	adapter 'handler' not found
2019-03-28T21:24:22.690107Z	error	Handler not found: handler='apigee-handler'
2019-03-28T21:24:22.690140Z	error	No valid actions found in rule
2019-03-28T21:24:22.797413Z	info	transport: loopyWriter.run returning. connection error: desc = "transport is closing"`

**Comment by theganyo** [comment]
That's good news. You're getting closer. Now we need to figure out why the mixer can't reach the adapter. Is it running?

`kubectl -n istio-system get deployment apigee-adapter`

**Comment by theganyo** [comment]
Also, why it's getting errors about the templates. Are they listed?

`kubectl -n istio-system get templates`

**Comment by walkerline** [comment]
1. It is running
kubectl -n istio-system get deployment apigee-adapter

Output:
NAME             DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
apigee-adapter   2         2         2            2           2d9h


2. no erros for the templates:

kubectl -n istio-system get templates

Output
NAME                   AGE
apigee-analytics       2d
apigee-authorization   2d

**Comment by theganyo** [comment]
Hey @walkerline... I apologize, I was out for a couple days and this accidentally got dropped. Where are we on this?
