### ISSUE TITLE
authentication-policy.yaml mtls line "upstream errors" fix

### ISSUE THREAD

**Issue by swilliams11** [apigee/istio-mixer-adapter#268]
This is a minor change to the the authentication-policy.yaml file.
https://github.com/apigee/istio-mixer-adapter/blob/master/samples/apigee/authentication-policy.yaml#L15

The following line
```
#  - mtls:   # uncomment if you're using mTLS between services in your mesh
```
should be changed to 
```
#  - mtls: {}  # uncomment if you're using mTLS between services in your mesh
```

If you leave it as then you still get the "upstream connect error or disconnect/reset before headers" error.  
```
- mtls:
```

When I execute `kubectl get policy auth-spec -o yaml`
partial output below.
```
peers:
  - {}
```

When I change the line to 
```
- mtls: {}
````
and execute `kubectl get policy auth-spec -o yaml` then I get the following partial output:
```
peers:
  - mtls: {}
```

The documentation for enabling Istio mutual auth is shown below.
https://istio.io/docs/tasks/security/authn-policy/#globally-enabling-istio-mutual-tls

**Comment by theganyo** [comment]
Thanks. Istio must have changed its interpretation of a nil config at some point. But using quotes is more correct, I'll change it.
