### ISSUE TITLE
support for self-signed certificates

### ISSUE THREAD

**Issue by dnewman866** [apigee/istio-mixer-adapter#270]
Apigee Adapter does not appear to support self-signed certificates. Enterprises that use the adapter internally to connect to Apigee Edge for Private Cloud may want to use self-signed certificates. Either provide a way to support self-signed certificates, allow turning off certificate validation, or document that it is not supported and certificates must be signed by a well known CA.

**Comment by theganyo** [comment]
A potential workaround for now could be to build and use a new docker image based off of the officially published image that copies the self-signed cert .crt file into the /etc/ssl/certs directory. See the debug [Dockerfile](https://github.com/apigee/istio-mixer-adapter/blob/master/grpc-server/Dockerfile_debug#L2) for an example of how this is done for the standard cert roots.

**Comment by theganyo** [comment]
In addition to the workaround above, SSL certificate validation may now be turned off via config `allowUnverifiedSSLCert: true`.

**Comment by theganyo** [comment]
Closing as resolved per the `allowUnverifiedSSLCert` configuration option.
