### ISSUE TITLE
[Question]: How does cache invalidation in adapter works?

### ISSUE THREAD

**Issue by AshishThakur** [apigee/istio-mixer-adapter#274]
As per https://docs.apigee.com/api-platform/istio-adapter/operation 

> When it starts up, the Apigee adapter obtains configuration information, including Product configurations, from Apigee Edge. For performance reasons, the Apigee adapter maintains a locally cached counter that it checks and decrements. Periodically, the Adapter synchronizes its quota count with the quota state maintained on Apigee Edge.

Was wondering how does cache invalidation happens. The document does mention that adapter synchronises this quota, what is the frequency at which this synchronisation happens?

**Comment by theganyo** [comment]
Synchronization with the server happens each minute.

**Comment by AshishThakur** [comment]
Thanks @theganyo. Is that a configuration which can be changed?

**Comment by theganyo** [comment]
Not currently, but it's certainly something that could be exposed. Do you need this?

**Comment by theganyo** [comment]
Oh, I should mention: Synchronization is also triggered whenever a quota is hit on the client. The once per minute is just to pick up any changes from the server when the client quota isn't being hit.
