### ISSUE TITLE
[Question]: JWT provider

### ISSUE THREAD

**Issue by AshishThakur** [apigee/istio-mixer-adapter#284]
Is it mandatory to use APIGee as JWT token provider or can we use other services like Okta, Auth0 as well?

**Comment by theganyo** [comment]
Other JWT providers may be used, but the adapter expects a few fields to be present. Here's an example JWT as generated by Apigee:
```
{
	"access_token": "YHFlv9IfBDkqwEF8yofxhCGU7ed",
	"api_product_list": [
		"hello"
	],
	"application_name": "hello",
	"aud": "istio",
	"client_id": "BB8hRvqJICSDFHaeof6fvo4qXzW1f8N",
	"developer_email": "details@test.com",
	"exp": 1543970392,
	"iat": 1543969492,
	"iss": "https://myorg-test.apigee.net/istio-auth/token",
	"jti": "3fb8dc5f-ba73-4cc3-95b1-6bad18e43e33",
	"nbf": 1543969492
}
```
Note these Apigee fields:
- api_product_list
- client_id
- application_name
- access_token
- developer_email

The first three are required for authentication, while the remaining are just passed to analytics.
