### ISSUE TITLE
the server could not find the requested resource (post apigees.config.istio.io)

### ISSUE THREAD

**Issue by walkerline** [apigee/istio-mixer-adapter#285]
Hi
When we run below command to install adapter, 

> kubectl apply -f samples/apigee/grpc

we see this error:
Error from server (NotFound): error when creating "samples/apigee/grpc/handler.yaml": the server could not find the requested resource (post apigees.config.istio.io)

Can you help?

**Comment by walkerline** [comment]
Ok.
issue got resolved by putting -g parameter when generate the handler.yaml file during provisioning.
Please correct your documentation as it does not mention this at all

**Comment by theganyo** [comment]
I apologize for the confusion, the README.md that came with your download should have that information, but the live documentation on github has been updated for a new release that will no longer require the -g option.
