### ISSUE TITLE
Streamline adapter code to gRPC only

### ISSUE THREAD

**Issue by theganyo** [apigee/istio-mixer-adapter#297]
Because of legacy reasons, the adapter code currently has both a internal adapter for compiling into Mixer and a gRPC wrapper. The internal code is no longer necessary and the adapter should be streamlined to only support the gRPC interface.

**Comment by theganyo** [comment]
This should take unto consideration Istio 1.5 mixer deprecation. See also #335.

**Comment by StevenACoffman** [comment]
Does Apigee support HTTP/2 (and gRPC)? 	
[The Source code has this comment](https://github.com/apigee/istio-mixer-adapter/blob/master/apigee-istio/cmd/root.go#L33)

**Comment by theganyo** [comment]
@StevenACoffman No, Apigee runtime does not. That said, Istio does, so the Istio Adapter does.

**Comment by StevenACoffman** [comment]
Oh bummer, I got super excited by this and thought we would see HTTP/2 and gRPC in apigee soon! (is that on the roadmap?)

**Comment by theganyo** [comment]
Sorry, I have no idea. Call your rep. :)
