### ISSUE TITLE
filtering liveness/readiness probe requests

### ISSUE THREAD

**Issue by arin-pang** [apigee/istio-mixer-adapter#312]
After install istio-mixer-adapter, our readiness/liveness probes failed due to istio rule.

>   Warning  Unhealthy  22m (x5 over 23m)  kubelet, ip-10-100-9-73.ec2.internal  Readiness probe failed: HTTP probe failed with statuscode: 401

It occurred a similar problem already in Kiali for Istio, and fixed this problem with changing match property in rule configuration.

istio/istio/issues/10336
istio/istio/pull/10480

**Comment by theganyo** [comment]
Very interesting! Thanks for the links.
