### ISSUE TITLE
Error Creating Credential: 404

### ISSUE THREAD

**Issue by vvunduru** [apigee/istio-mixer-adapter#320]
![image](https://user-images.githubusercontent.com/54122313/70256299-df083880-174d-11ea-8c0e-34c3aa718586.png)

I m trying to provision apigee-Istio and I m getting this issue. Can someone please help me with this.

Below is the command I used.
![image](https://user-images.githubusercontent.com/54122313/70256663-766d8b80-174e-11ea-95d4-3d5ad5d87a19.png)

Thank you,

**Comment by theganyo** [comment]
Apigee probably failed to deploy the proxy. Please try the command again adding the `--forceProxyInstall` option.
