### ISSUE TITLE
Adaptor multiple environments 

### ISSUE THREAD

**Issue by gareth-bird** [apigee/istio-mixer-adapter#328]
Is there guidance on how you can use/configure the mixer adaptor to support multiple Apigee environments (say Dev, Integration, Test).  In effect, this is a segregation / tenancy question.

'apigee-istio provision ...' creates a handler for one apigee environment.  How could multiple apigee environments work within the context of a single istio control plane/mixer; run multi adaptors containers in -n istio-system?  

Clearly istio doesn't currently have a  model for soft multi tenancy, i.e. the idea of isolating different control planes in different namespaces isn't available, which means it's not clear how you'd setup multiple staging environments in a k8 cluster.  

Any thoughts appreciated.

**Comment by theganyo** [comment]
You actually have two options:

1. Multi-tenant adapter: Use multiple handlers pointed at a single adapter service.
2. Single-tenant adapter: Use multiple handlers and point each handler at a different adapter.

Either way should work, depending on your isolation needs.

**Comment by gareth-bird** [comment]
Makes sense.  Thank you for the timely reply Ganyo, really appreciated.
