### ISSUE TITLE
On Prem Apigee - management base

### ISSUE THREAD

**Issue by gareth-bird** [apigee/istio-mixer-adapter#329]
istio-auth proxy is not configured with the correct management base, if the -m option is used.  This is needed when configuring the adaptor to run with edge on prem.  The 'Authenticate Call' policy is hard coded with the cloud base https://edgemicroservices.apigee.net rather than use the machine base specified on the command line.

**Comment by theganyo** [comment]
Thanks, I'll take a look. In the meantime, while obviously not optimal, you could manually change this in your proxy after provisioning. Does that work?

**Comment by gareth-bird** [comment]
Indeed this is what I did, and it does work.  Thank you.

Would you like this issue closed now, or left open to trigger a story?

**Comment by theganyo** [comment]
Please leave it. I'll keep this for tracking. Thanks!

**Comment by theganyo** [comment]
Correction on original issue description: The istio-auth proxy needs to reference the routerBase, not the managementBase.
