### ISSUE TITLE
Istio 1.6 and the future of apigee-istio

### ISSUE THREAD

**Issue by anhdle14** [apigee/istio-mixer-adapter#342]
Istio released 1.6, and I think most of the guides and integration between Apigee and Istio is broken. Mixer is soon to be deprecated, is there any future plan on this. I would love to be working on fixing and migrating from Mixer.

**Comment by theganyo** [comment]
Thanks for your interest! I’d be interested to know what you’ve seen that’s broken. Yes, I have been working on a replacement that is tied only to envoy and an official announcement will be forthcoming very soon.

**Comment by anhdle14** [comment]
I will try to document what goes wrong in Istio 1.6. Is using the free 60 days in Apigee ok enough for the test? (There are some differences in the UI and some functionalities, just making sure)

**Comment by theganyo** [comment]
Yes, the trial version should work just fine. I really appreciate you letting me know anything you find!

**Comment by anhdle14** [comment]
This will be a long post, lol!

---
# Environment
```bash
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.8-gke.15", GitCommit:"9cabee15e0922c3b36724de4866a98f6c2da5e6a", GitTreeState:"clean", BuildDate:"2020-05-01T21:47:04Z", GoVersion:"go1.13.8b4", Compiler:"gc", Platform:"linux/amd64"}

$ istioctl version 
# 1.5 is the introduction of istiod, so I tested with 1.5.4, but 1.6 should be the same.
client version: 1.5.4
control plane version: 1.5.4
data plane version: 1.5.4 (4 proxies)

$ apigee-istio version
# build from commit ee8d9f26fa75ead17e800aeef3f72eb27204da5a
apigee-istio version dev unknown [unknown]

$ cat samples/apigee/adapter.yaml | grep "image: .*"
image: "gcr.io/apigee-api-management-istio/apigee-adapter:nightly"
```

## Additional Istioctl

```bash
$ istioctl manifest apply --set profile=demo
- Applying manifest for component Base...
✔ Finished applying manifest for component Base.
- Applying manifest for component Pilot...
✔ Finished applying manifest for component Pilot.
  Waiting for resources to become ready...
  Waiting for resources to become ready...
  Waiting for resources to become ready...
  Waiting for resources to become ready...
- Applying manifest for component IngressGateways...
- Applying manifest for component EgressGateways...
- Applying manifest for component AddonComponents...
✔ Finished applying manifest for component EgressGateways.
✔ Finished applying manifest for component IngressGateways.
✔ Finished applying manifest for component AddonComponents.

$ kubectl -n istio-system get cm istio -o jsonpath="{@.data.mesh}" | grep disablePolicyChecks
# ❌ This one is broken, depracated on istio.io/docs 
disablePolicyChecks: true
```

## Reproduce 

I strictly followed this: https://docs.apigee.com/api-platform/istio-adapter/install-istio_1_1

### Apigee UI

First is the Apigee UI error: https://docs.apigee.com/api-platform/istio-adapter/install-istio_1_1#3_create_an_api_product. This has been updated to new UI and there is no textbox to enter istio-services. I have to manually running `$ apigee-istio bindings add helloworld.default.svc.cluster.local hello-istio-product -u $USERNAME -p $PASSWORD -o $ORG -e $ENV` to understand where it is.

![](https://i.imgur.com/n6NPc6K.png)

### Apigee Authorization with `x-api-key`

During the step: https://docs.apigee.com/api-platform/istio-adapter/install-istio_1_1#configure_the_apigee_adapter

```bash
$ kubectl apply -f samples/apigee/
deployment.apps/apigee-adapter unchanged
service/apigee-adapter unchanged
policy.authentication.istio.io/auth-spec unchanged
instance.config.istio.io/apigee-authorization unchanged
instance.config.istio.io/apigee-analytics unchanged
template.config.istio.io/apigee-authorization unchanged
template.config.istio.io/apigee-analytics unchanged
adapter.config.istio.io/apigee unchanged
handler.config.istio.io/apigee-handler unchanged
rule.config.istio.io/apigee-rule unchanged

$ curl http://$HELLOWORLD_URL/hello
# This still show 200 while documents showing "PERMISSION_DENIED:apigee-handler.apigee.istio-system:missing authentication"
Hello version: v1, instance: helloworld-v1-578dd69f69-dnfh2
```

I tried the debugging tips from the wiki but there are no Mixer pods to get logs.

Also, the Quota won't work because it relied on the Header of `x-api-key`.

### JWT
JWT does work because this is still a valid API. But this is going to change soon.

I use `$ apigee-istio` to create and pass the token and this is working fine.

```bash
$ cat samples/apigee/authentication-policy.yaml
---
# Define an Istio Auth Policy
apiVersion: "authentication.istio.io/v1alpha1"
kind: Policy
metadata:
  name: auth-spec
  namespace: default
spec:
  targets:
  - name: helloworld
  peers: []
#  - mtls: {}  # uncomment if you're using mTLS between services in your mesh
  origins:
  - jwt:
      issuer: https://$ORG-$ENV.apigee.net/istio-auth/token
      jwks_uri: https://$ORG-$ENV.apigee.net/istio-auth/certs
  principalBinding: USE_ORIGIN
```

**Comment by theganyo** [comment]
I believe the key is for you to install istio with the policy enabled. Try this:

`istioctl manifest apply --set profile=demo --set components.policy.enabled=true`

**Comment by anhdle14** [comment]
```
$ kubectl -n istio-system get cm istio -o jsonpath="{@.data.mesh}" | grep disablePolicyChecks
disablePolicyChecks: false
```
The docs on istio mentioned this, but this does solve the PolicyChecks.
> Alternatively, you may install Istio using the demo profile, which enables policy checks by default.

But `x-api-key` still doesn't work.

**Comment by theganyo** [comment]
The other thing I noticed offhand is that you don't seem to be using a released version?
```
$ apigee-istio version
# build from commit ee8d9f26fa75ead17e800aeef3f72eb27204da5a
apigee-istio version dev unknown [unknown]
```

I'd recommend sticking to a released version. The release is known to work with Istio 1.5 and you said you're using 1.5.  So, I'd start over with the latest release and use `-f` for provisioning to ensure you get the correct proxy. Then, I'd walk through this: https://github.com/apigee/istio-mixer-adapter/wiki/Debug-Authorization-check-in-Istio-1.1.x

**Comment by theganyo** [comment]
Update: With the deprecation of Istio's Mixer and policy support, we have created a new project that relies only on Envoy, but still integrates with and allows policy control in Istio. Please check out the [Apigee Envoy Adapter](https://docs.apigee.com/api-platform/envoy-adapter/concepts) project.

**Comment by galo** [comment]
Is the Apigee Envoy Adapter code available ?

**Comment by theganyo** [comment]
Yes, all source code is available.
https://github.com/apigee/apigee-remote-service-envoy
https://github.com/apigee/apigee-remote-service-cli
https://github.com/apigee/apigee-remote-service-golib
