### ISSUE TITLE
add codecov

### ISSUE THREAD

**Issue by theganyo** [apigee/istio-mixer-adapter#38]

**Comment by theganyo** [comment]
Github access requested for CodeCov.io. Once granted, we can add integration. See: https://circleci.com/docs/1.0/code-coverage/#codecov

**Comment by theganyo** [comment]
@SindhuSreedharan Is this something you can get granted for our repo?

**Comment by SindhuSreedharan** [comment]
Its approved now. Please proceed with integration.
