### ISSUE TITLE
Support Mixer on CentOS/RHEL

### ISSUE THREAD

**Issue by srinandan** [apigee/istio-mixer-adapter#42]
Create Mixer binary for RHEL/CentOS (6.X and 7.X)

**Comment by theganyo** [comment]
CircleCI only provides Ubuntu for builds.

**Comment by theganyo** [comment]
Correction: We *can* do this in a docker container. This project could generate the binary and copy it to a bucket on the GCP project for Anchor to pick up.

However, given that this output binary is really only useful to the Anchor project and only needed for Anchor releases, I'm not certain that doing it as a part of this project's CI makes sense. I believe that Anchor will have to make a CentOS-specific compile of the rest of Istio anyway, correct?
