### ISSUE TITLE
Question about HTTPAPISpec

### ISSUE THREAD

**Issue by galo** [apigee/istio-mixer-adapter#43]
On the Istio [docs](https://istio.io/docs/reference/config/istio.mixer.v1.config.client.html) attributes is an array of attributes, while in https://github.com/apigee/istio-mixer-adapter/blob/master/install/api-spec.yaml#L25-L30 there are two nested attributes is that a issue?

**Comment by theganyo** [comment]
Good question. It looks like Istio may have fixed a previous issue with attributes. We'll need to test the new format. Thanks.
