### ISSUE TITLE
add developer_email to JWT token and send to analytics

### ISSUE THREAD

**Issue by theganyo** [apigee/istio-mixer-adapter#47]
Edge micro tokens don't include a developer_email claim in JWT, so we can't support it. However, it is an analytics field, so it would be nice to include.

**Comment by srinandan** [comment]
do you need the developer email or developer id?

**Comment by theganyo** [comment]
I believe developer_email would be most useful. For example, the "Developer Engagement" dashboard uses the email.

**Comment by theganyo** [comment]
Tried: 
```
npm -g up edgemicro
edgemicro upgradeauth ...
```
Seemed to success. However, now getting token fails: 
```
edgemicro token get ...
{ fault:
   { faultstring: 'Unable to identify proxy for host: theganyo1-eval-prod.apigee.net:443 and url: /edgemicro-auth/token',
     detail: { errorcode: 'messaging.adaptors.http.flow.ApplicationNotFound' } } }
```
Rolled back the EM auth proxy.

**Comment by theganyo** [comment]
fix was made to edgemicro, after reinstall and proxy upgrade it now works
