### ISSUE TITLE
mixer reporting 'adapter did not close all the scheduled daemons' on configuration reload

### ISSUE THREAD

**Issue by theganyo** [apigee/istio-mixer-adapter#5]
Error from logs:
```
2018-03-13T00:45:49.257730Z	error	adapter did not close all the scheduled daemons	{"adapter": "apigee-handler.apigee.istio-system"}
```

**Comment by robbrit** [comment]
How did you produce this error? When I run mixer locally and Ctrl-C it, it doesn't log anything.

**Comment by theganyo** [comment]
This is produced when applying a new mixer adapter configuration to the running mixer. Note: It's not high priority as it continues to work.

**Comment by theganyo** [comment]
Further investigation reveals that this is likely just false positives from Mixer. See: https://github.com/istio/istio/blob/master/mixer/pkg/runtime/handler/env.go#L102
