### ISSUE TITLE
JWT application_name is mandatory?

### ISSUE THREAD

**Issue by galo** [apigee/istio-mixer-adapter#52]
The  "application_name" claim seems mandatory for authz to work, failing to pass the claim ina a JWT generates this trace

2018-04-12T22:39:15.888716Z	error	authenticate err: unable to interpret application_name: <nil>	{"adapter": "apigee-handler.apigee.istio-system"}

I wonder if this is by design, since the clientId is basically the identifier of the application, maybe this can be an optional claim.

**Comment by theganyo** [comment]
The driving factor here is that application name is static whereas client_id can be revoked.

**Comment by galo** [comment]
LGTM
