### ISSUE TITLE
CLI: location for credential

### ISSUE THREAD

**Issue by srinandan** [apigee/istio-mixer-adapter#95]
When generating the credentials, we need to know which location endpoint to use. The location endpoint depends on where the org is hosted. The logic [here](https://github.com/apigee/istio-mixer-adapter/blob/master/apigee-istio/cmd/provision/provision.go#L107) does not appear to take that into consideration.

See MG's logic [here](https://github.com/apigee-internal/microgateway/blob/master/cli/lib/key-gen.js) for more details

**Comment by theganyo** [comment]
Can you be more specific? I believe all the URLs used are dependent on values passed in by the user.

**Comment by srinandan** [comment]
Here is the endpoint we have defined for public cloud: `https://edgemicroservices.apigee.net/edgemicro/`

However, the endpoint `edgemicroservices.apigee.net` is dependent on the ORG's location (ex: us-east vs. us-west). For example, org amer-demo13 is in us-east, so the endpoint is: `edgemicroservices-us-east-1.apigee.net`

In Microgateway, the location for amer-demo13 is gotten by calling `https://edgemicroservices.apigee.net/edgemicro/region/organization/amer-demo13/environment/test`

**Comment by theganyo** [comment]
It seems to work without the region change, but I need more details about how to test. For example, I can provision and create quotas without any changes... but is this sufficient verification?

**Comment by srinandan** [comment]
I think the best way to test is to create a GCP VM in APAC/EMEA, then try and access a org hosted in the US. In theory, the call should be routed to `apigee-internal` in EMEA. We can try Quota, Credentials. If this test works with no changes, we can close this for now.

**Comment by theganyo** [comment]
Started a machine in Taiwan... provisioned from there against my org/env, accessed quotas, accessed region, etc. Calling this ok. We can open a new issue if someone finds a regional issue.
